language: php
sudo: required
dist: bionic
php:
  - '7.2'

services:
  - mysql

before_install:
  - sudo apt-get update -q
  - sudo apt-get install calibre epubcheck -y

install:
  - composer install
  - mysql -e "CREATE DATABASE wsexport_test;" -uroot
  - sed --in-place "s/DBNAME/wsexport_test/" config.php
  - sed --in-place "s/DBUSERNAME/travis/" config.php

script:
  - composer test
  - ./vendor/bin/phpunit
