language: php
sudo: required
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_install:
  - sudo apt-get update -q
  - sudo apt-get install calibre-bin default-jre -y

install:
  - make install

script:
  - make test
  - make composer-test
  - make integration-test
