
sudo: required
dist: trusty

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq --force-yes calibre-bin
  - phpenv install 5.6.13
  - phpenv global 5.6.13
  - php --version

install:
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install

script:
  - make test
  - make integration-test
  - php composer.phar test
