language: php
sudo: required
dist: trusty
php:
  - '5.5'
  - '7.1'
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_install:
  - sudo apt-get update -q
  - sudo apt-get install calibre-bin default-jre -y

install:
  - make install

before_script:
  - make composer-test

script:
  - make test
  - make integration-test
