version: '3.7'
services:
  wsexport:
    build: ./
    user: "${WS_DOCKER_UID}:${WS_DOCKER_GID}"
    ports:
      - "${WS_DOCKER_PORT}:8080"
    volumes:
      - ./:/var/www/html:cached
    links:
      - database:database
    environment:
      APACHE_RUN_USER: daemon
  database:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=wsexport
