name: CI

on: [push, pull_request]

jobs:
  build:

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: wsexport_test
          MYSQL_ROOT_PASSWORD: testpwd
        ports:
          - '3306:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    env:
      APP_ENV: test
      DATABASE_URL: mysql://root:testpwd@127.0.0.1:3306/wsexport_test?serverVersion=5.7

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php: [ '7.2' ]

    runs-on: ${{matrix.os}}

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{matrix.php}}
        extensions: pdo, imagick

    - name: Install Calibre and epubcheck
      run: |
        sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin
        sudo apt-get update -q
        sudo apt-get install epubcheck -y

    - name: Install WSExport
      run: |
        composer install

    - name: Test
      run: |
        composer test
        ./bin/phpunit --exclude-group=exclude-from-ci
